# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 257)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 360, 61))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 66, 18))
        self.label.setObjectName("label")
        self.totalLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.totalLabel.setGeometry(QtCore.QRect(100, 32, 150, 18))
        self.totalLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.totalLabel.setObjectName("totalLabel")
        self.resetButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.resetButton.setGeometry(QtCore.QRect(270, 28, 80, 26))
        self.resetButton.setObjectName("resetButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 360, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 66, 18))
        self.label_2.setObjectName("label_2")
        self.chargeButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.chargeButton.setGeometry(QtCore.QRect(270, 28, 80, 26))
        self.chargeButton.setObjectName("chargeButton")
        self.chargeEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.chargeEdit.setGeometry(QtCore.QRect(100, 30, 150, 26))
        self.chargeEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.chargeEdit.setObjectName("chargeEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 360, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 66, 18))
        self.label_3.setObjectName("label_3")
        self.paymentButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.paymentButton.setGeometry(QtCore.QRect(270, 28, 80, 26))
        self.paymentButton.setObjectName("paymentButton")
        self.paymentEdit = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.paymentEdit.setGeometry(QtCore.QRect(100, 30, 150, 26))
        self.paymentEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.paymentEdit.setObjectName("paymentEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "카드 단말기"))
        self.groupBox.setTitle(_translate("Dialog", "카드 정보"))
        self.label.setText(_translate("Dialog", "현재 잔액: "))
        self.totalLabel.setText(_translate("Dialog", "0"))
        self.resetButton.setText(_translate("Dialog", "초기화"))
        self.groupBox_2.setTitle(_translate("Dialog", "충전"))
        self.label_2.setText(_translate("Dialog", "충전 잔액: "))
        self.chargeButton.setText(_translate("Dialog", "충전"))
        self.groupBox_3.setTitle(_translate("Dialog", "결제"))
        self.label_3.setText(_translate("Dialog", "결제 잔액: "))
        self.paymentButton.setText(_translate("Dialog", "결제"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
