# Form implementation generated from reading ui file 'opencv.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 489)
        self.btnOpen = QtWidgets.QPushButton(parent=Dialog)
        self.btnOpen.setGeometry(QtCore.QRect(440, 20, 88, 26))
        self.btnOpen.setObjectName("btnOpen")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 70, 510, 310))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnCamera = QtWidgets.QPushButton(parent=Dialog)
        self.btnCamera.setGeometry(QtCore.QRect(340, 20, 88, 26))
        self.btnCamera.setObjectName("btnCamera")
        self.btnRecord = QtWidgets.QPushButton(parent=Dialog)
        self.btnRecord.setGeometry(QtCore.QRect(240, 20, 88, 26))
        self.btnRecord.setObjectName("btnRecord")
        self.label2 = QtWidgets.QLabel(parent=Dialog)
        self.label2.setGeometry(QtCore.QRect(20, 20, 66, 18))
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.btnCapture = QtWidgets.QPushButton(parent=Dialog)
        self.btnCapture.setGeometry(QtCore.QRect(140, 20, 88, 26))
        self.btnCapture.setObjectName("btnCapture")
        self.btnOpenVideo = QtWidgets.QPushButton(parent=Dialog)
        self.btnOpenVideo.setGeometry(QtCore.QRect(440, 400, 88, 26))
        self.btnOpenVideo.setObjectName("btnOpenVideo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnOpen.setText(_translate("Dialog", "OpenFile"))
        self.btnCamera.setText(_translate("Dialog", "Camera On"))
        self.btnRecord.setText(_translate("Dialog", "Rec Start"))
        self.btnCapture.setText(_translate("Dialog", "Capture"))
        self.btnOpenVideo.setText(_translate("Dialog", "Open Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
