# Form implementation generated from reading ui file 'TCPClient.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 300)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 510, 100))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 50, 81, 18))
        self.label.setObjectName("label")
        self.ipEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.ipEdit.setGeometry(QtCore.QRect(110, 45, 141, 26))
        self.ipEdit.setObjectName("ipEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 30, 18))
        self.label_2.setObjectName("label_2")
        self.portEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.portEdit.setGeometry(QtCore.QRect(330, 45, 60, 26))
        self.portEdit.setObjectName("portEdit")
        self.connectButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.connectButton.setGeometry(QtCore.QRect(400, 45, 88, 26))
        self.connectButton.setObjectName("connectButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 120, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.led21 = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.led21.setGeometry(QtCore.QRect(10, 40, 92, 24))
        self.led21.setObjectName("led21")
        self.led22 = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.led22.setGeometry(QtCore.QRect(10, 70, 92, 24))
        self.led22.setObjectName("led22")
        self.led23 = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.led23.setGeometry(QtCore.QRect(10, 100, 92, 24))
        self.led23.setObjectName("led23")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 120, 370, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 110, 18))
        self.label_3.setObjectName("label_3")
        self.degreeEdit = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.degreeEdit.setGeometry(QtCore.QRect(150, 40, 100, 26))
        self.degreeEdit.setObjectName("degreeEdit")
        self.moveButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.moveButton.setGeometry(QtCore.QRect(260, 40, 88, 26))
        self.moveButton.setObjectName("moveButton")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(160, 200, 371, 60))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 140, 18))
        self.label_4.setObjectName("label_4")
        self.sensorEdit = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.sensorEdit.setGeometry(QtCore.QRect(240, 20, 110, 26))
        self.sensorEdit.setReadOnly(True)
        self.sensorEdit.setObjectName("sensorEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "TCP Server"))
        self.label.setText(_translate("Dialog", "IP Address"))
        self.label_2.setText(_translate("Dialog", "Port"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.groupBox_2.setTitle(_translate("Dialog", "LED"))
        self.led21.setText(_translate("Dialog", "LED 21"))
        self.led22.setText(_translate("Dialog", "LED 22"))
        self.led23.setText(_translate("Dialog", "LED 23"))
        self.groupBox_3.setTitle(_translate("Dialog", "Sevo Motor"))
        self.label_3.setText(_translate("Dialog", "Target Degree"))
        self.moveButton.setText(_translate("Dialog", "Move"))
        self.label_4.setText(_translate("Dialog", "Phororesistor Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
